# Use the official Ubuntu image as a base
FROM ubuntu:20.04

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    openjdk-11-jdk \
    python3 \
    python3-pip \
    npm \
    && apt-get clean

ENV PATH="/usr/bin/python3:${PATH}"

# Install PySpark
RUN pip3 install pyspark

# Install delta-spark
RUN pip3 install delta-spark

#install NodeJS 22
RUN curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install -y nodejs
RUN node -v

#RUN wget https://repo1.maven.org/maven2/io/delta/delta-core_2.12/2.4.0/delta-core_2.12-2.4.0.jar -P /root/.ivy2/jars 
RUN wget https://repo1.maven.org/maven2/io/delta/delta-spark_2.13/3.3.0/delta-spark_2.13-3.3.0.jar -P /root/.ivy2/jars 

RUN mkdir -p /shared-data
RUN chmod -R 755 ./shared-data

RUN mkdir -p /scripts
RUN chmod -R 755 ./scripts

# Set the working directory
WORKDIR /app

# Copy your application code to the container
COPY . /app

# Install Node.js dependencies
RUN npm install

# Expose ports if needed
EXPOSE 3000

# Default command to run your Node.js application
CMD ["node", "src/index.js"]
#CMD ["tail", "-f", "/dev/null"]